### ISSUE TITLE
some codes are required for disconnected graphs maybe?

### ISSUE THREAD

**Issue by sungjun3010** [GTmac/HARP#11] opened 2019-09-01 08:48 UTC
hi, i'm trying to apply your method to my project.

but when i ran the code with my graph disconnected, there is an index error for sub-graphs except largest one (at graph_coarsening.py - skipgram_coarsening_disconnected function).
i think that is because you give the parameter 'recursive_graphs' to skipgram_coarsening_hs function (line 307) without newly initialize for next sub-graphs.

Am i understood your code right?
then,  i suggest you add a code like 'recursive_graphs = None' at line between 343 and 344.

**Comment by GTmac** [comment] 2019-09-03 01:02
Are you referring to this line: https://github.com/GTmac/HARP/blob/master/src/graph_coarsening.py#L298

Not sure what the problem is -- I tried some disconnected graphs and it works well. `recursive_graphs` is an array of graphs, what do you mean by "newly initialize for next subgraphs"?

**Comment by sungjun3010** [comment] 2019-09-03 01:23
I think 'recursive_graphs' should be generated for each subgraph because they are disconnected.
from the loop statement:
[](https://github.com/GTmac/HARP/blob/src/graph_coarsening.py#L273)

At the first iteration, 'recursive_graphs' is generated by the first subgraph.
then at the second iteration, 'recursive_graphs' should be re-generated by the second subgraph.
but 'recursive_graphs' do not  re-generated because 'recursive_graphs' is not None.
So I think any code is needed to set 'recursive_graphs' to None before the next iteration.

**Comment by GTmac** [comment] 2019-09-04 00:44
Oh I see what you mean. I think you are right :) Nice catch! It would be great if you can help me with fixing it.

**Comment by sungjun3010** [comment] 2019-09-04 02:16
I feel good to help you. I just write a code
`recursive_graphs = None`  under [https://github.com/GTmac/HARP/blob/src/graph_coarsening.py#L333](https://github.com/GTmac/HARP/blob/f435d82d63f160587763f62c3902fe77b1671c3b/src/graph_coarsening.py#L333) with less indent and got a result!

**Comment by GTmac** [comment] 2019-09-06 03:50
Fixed now. Thanks again!

**Closed** 2019-09-06 18:44 UTC
